version: "3.3"
services:
    postgis:
        image: mdillon/postgis:9.6-alpine
        ports: 
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
    mongo:
        image: mongo
        ports: 
            - "27017:27017"
